# Generated by Django 4.2.2 on 2023-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
